services:
  grafana:
    user: root
    container_name: 'supsi-istsos4-grafana'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.3}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3006:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/supsi-istsos4
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/supsi-istsos4

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.supsi-istsos4:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: supsi-istsos4
      GF_INSTALL_PLUGINS: orchestracities-map-panel


      # Lines for Embedding 
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      # GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
